[package]
name = "action_msgs"
version = "1.2.1"
edition = "2021"

[features]
default = []
std = ["nano-ros-core/std", "nano-ros-serdes/std", "unique_identifier_msgs/std", "builtin_interfaces/std"]

[dependencies]
# nano-ros crates (patched to local via .cargo/config.toml during development)
nano-ros-core = { version = "*", default-features = false }
nano-ros-serdes = { version = "*", default-features = false }
heapless = "0.8"
unique_identifier_msgs = { path = "../unique_identifier_msgs", default-features = false }
builtin_interfaces = { path = "../builtin_interfaces", default-features = false }
