[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[env]
DEFMT_LOG = "trace"

[patch.crates-io]
nano-ros-core = { path = "../../crates/nano-ros-core" }
nano-ros-serdes = { path = "../../crates/nano-ros-serdes" }
builtin_interfaces = { path = "generated/builtin_interfaces" }
std_msgs = { path = "generated/std_msgs" }
