[patch.crates-io]
nano-ros-core = { path = "../../crates/nano-ros-core" }
nano-ros-serdes = { path = "../../crates/nano-ros-serdes" }
zenoh-pico-shim = { path = "../../crates/zenoh-pico-shim" }
zenoh-pico-shim-sys = { path = "../../crates/zenoh-pico-shim-sys" }
builtin_interfaces = { path = "generated/builtin_interfaces" }
std_msgs = { path = "generated/std_msgs" }
