[package]
name = "nano-ros-params"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ROS 2 parameter server for nano-ros"

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
heapless = { workspace = true }
