[package]
name = "nano-ros-serdes"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CDR serialization/deserialization for nano-ros"

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
heapless = { workspace = true }
