[patch.crates-io]
nano-ros-core = { path = "/home/aeon/repos/rusty-ros/crates/nano-ros-core" }
nano-ros-serdes = { path = "/home/aeon/repos/rusty-ros/crates/nano-ros-serdes" }
builtin_interfaces = { path = "generated/builtin_interfaces" }
std_msgs = { path = "generated/std_msgs" }
